version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    volumes:
      - cassandra_data:/var/lib/cassandra
    ports:
      - "9042:9042"

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local
  cassandra_data:
    driver: local
